- src/main/java/shop/dalda/s3/S3ResponseDto.java
- src/main/java/shop/dalda/s3/S3UploadController.java
- src/main/java/shop/dalda/s3/S3UploadService.java
> DD-50-이미지-업로드-api

- src/main/java/shop/dalda/order/Order.java
- src/main/java/shop/dalda/order/OrderController.java
- src/main/java/shop/dalda/order/OrderService.java
- src/main/java/shop/dalda/order/dto/request/OrderRequestDto.java
- src/main/java/shop/dalda/order/dto/response/OrderListForCompanyResponseDto.java
- src/main/java/shop/dalda/order/dto/response/OrderListForConsumerResponseDto.java
- src/main/java/shop/dalda/order/dto/response/OrderResponseDto.java
- src/main/java/shop/dalda/s3/S3ResponseDto.java
- src/main/java/shop/dalda/s3/S3UploadController.java
[DD-63] [DD-71]
오더 및 이미지 업로드 API Swagger 연동
[DD-63]: https://jonghyuklee.atlassian.net/browse/DD-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DD-71]: https://jonghyuklee.atlassian.net/browse/DD-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DD-61-스웨거-연동-ms

- src/main/java/shop/dalda/order/Order.java
- src/main/java/shop/dalda/order/OrderController.java
- src/main/java/shop/dalda/order/OrderService.java
- src/main/java/shop/dalda/order/dto/request/OrderRequestDto.java
- src/main/java/shop/dalda/order/dto/response/OrderListForCompanyResponseDto.java
- src/main/java/shop/dalda/order/dto/response/OrderListForConsumerResponseDto.java
- src/main/java/shop/dalda/order/dto/response/OrderResponseDto.java
- src/main/java/shop/dalda/template/Template.java
- src/main/java/shop/dalda/template/TemplateController.java
- src/main/java/shop/dalda/template/TemplateService.java
- src/main/java/shop/dalda/template/dto/request/TemplateRequestDto.java
- src/main/java/shop/dalda/template/dto/request/TemplateUpdateRequestDto.java
- src/main/java/shop/dalda/template/dto/response/TemplateListResponseDto.java
- src/main/java/shop/dalda/template/dto/response/TemplateResponseDto.java
- src/main/java/shop/dalda/template/dto/response/TemplateUpdateResponseDto.java
템플릿 API 메서드의 기능 및 파라미터 설명 추가 For Swagger
+ Template 클래스에 JPA Auditing, 지연 로딩 적용
> DD-62-템플릿-api-swagger-연동

- src/main/java/shop/dalda/order/OrderController.java
- src/main/java/shop/dalda/order/OrderService.java
- src/main/java/shop/dalda/order/dto/request/OrderRequestDto.java
- src/main/java/shop/dalda/order/dto/response/OrderListForCompanyResponseDto.java
- src/main/java/shop/dalda/order/dto/response/OrderListForConsumerResponseDto.java
- src/main/java/shop/dalda/order/dto/response/OrderResponseDto.java
- src/main/java/shop/dalda/template/TemplateController.java
- src/main/java/shop/dalda/template/TemplateService.java
- src/main/java/shop/dalda/template/dto/request/TemplateRequestDto.java
- src/main/java/shop/dalda/template/dto/request/TemplateUpdateRequestDto.java
- src/main/java/shop/dalda/template/dto/response/TemplateListResponseDto.java
- src/main/java/shop/dalda/template/dto/response/TemplateResponseDto.java
- src/main/java/shop/dalda/template/dto/response/TemplateUpdateResponseDto.java
> DD-73-security-적용

- src/main/java/shop/dalda/exception/BadRequestException.java
- src/main/java/shop/dalda/exception/OAuthProcessingException.java
- src/main/java/shop/dalda/security/auth/OAuth2AuthenticationFailureHandler.java
- src/main/java/shop/dalda/security/auth/OAuth2AuthenticationSuccessHandler.java
- src/main/java/shop/dalda/security/jwt/JwtAuthenticationFilter.java
- src/main/java/shop/dalda/security/jwt/TokenProvider.java
- src/main/java/shop/dalda/user/ui/UserAuthController.java
- src/main/java/shop/dalda/util/service/AuthService.java
[DD-83] JWT accessToken 전달방식 변경
[DD-83]: https://jonghyuklee.atlassian.net/browse/DD-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DD-83] JWT accessToken 전달방식 변경

- src/main/java/shop/dalda/order/Answer.java
- src/main/java/shop/dalda/order/AnswerConverter.java
- src/main/java/shop/dalda/order/JSONConverter.java
- src/main/java/shop/dalda/order/Order.java
- src/main/java/shop/dalda/order/OrderController.java
- src/main/java/shop/dalda/order/OrderService.java
- src/main/java/shop/dalda/order/dto/request/OrderRequestDto.java
- src/main/java/shop/dalda/order/dto/response/OrderResponseDto.java
- Answer 클래스 생성
- 주문 등록 시 답변 중복 처리 적용
- Converter 일반화
> DD-80-주문-등록-api

- src/main/java/shop/dalda/security/auth/CookieAuthorizationRequestRepository.java
- src/main/java/shop/dalda/security/auth/OAuth2AuthenticationSuccessHandler.java
로그인 이후 redirect 방식을 request시 요청 하는 방식에서 referer url로 변경
> [DD-86] 로그인 redirect 방식 변경

- src/main/java/shop/dalda/user/domain/User.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyRequest.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyResponse.java
profile 컬럼명을 profileImage로 변경했습니다.
> [DD-85] User Entity 컬럼명 변경

- src/main/java/shop/dalda/config/QueryDslConfig.java
- src/main/java/shop/dalda/order/application/OrderService.java
- src/main/java/shop/dalda/order/domain/Answer.java
- src/main/java/shop/dalda/order/domain/Order.java
- src/main/java/shop/dalda/order/domain/OrderStatus.java
- src/main/java/shop/dalda/order/domain/repository/OrderRepository.java
- src/main/java/shop/dalda/order/domain/repository/OrderRepositoryCustom.java
- src/main/java/shop/dalda/order/domain/repository/OrderRepositoryImpl.java
- src/main/java/shop/dalda/order/ui/OrderController.java
- src/main/java/shop/dalda/order/ui/dto/request/OrderRequestDto.java
- src/main/java/shop/dalda/order/ui/dto/response/OrderCountResponseDto.java
- src/main/java/shop/dalda/order/ui/dto/response/OrderListForCompanyResponseDto.java
- src/main/java/shop/dalda/order/ui/dto/response/OrderListForConsumerResponseDto.java
- src/main/java/shop/dalda/order/ui/dto/response/OrderResponseDto.java
- 주문 개수 조회 API 추가
- Querydsl Config 파일 추가
- Order 패키지 디렉토리 구조 재구성
> DD-87-DD-88-주문-API

- src/main/java/shop/dalda/user/domain/User.java
- src/main/java/shop/dalda/user/domain/repository/UserRepositoryImpl.java
User Entity
변경된 Order의 경로가 Import에 반영되지 않은 것 수정
컬럼 profile -> profileImage 반영되지 않은 것 수정
> import 오타 수정

- build.gradle
- src/main/java/shop/dalda/exception/order/OrderNotBelongToUserException.java
- src/main/java/shop/dalda/order/application/OrderService.java
- src/main/java/shop/dalda/order/domain/Order.java
- src/main/java/shop/dalda/order/ui/OrderController.java
- src/main/java/shop/dalda/order/ui/dto/request/OrderRequestDto.java
- src/main/java/shop/dalda/order/ui/dto/request/OrderUpdateRequestDto.java
- src/main/java/shop/dalda/order/ui/dto/response/OrderUpdateResponseDto.java
- src/main/java/shop/dalda/order/ui/mapper/AnswerConverter.java
- src/main/java/shop/dalda/order/ui/mapper/OrderMapper.java
- 주문 수정 API 추가
-> Querydsl, MapStruct 사용
> DD-91-주문-수정-api

- src/main/java/shop/dalda/order/application/OrderService.java
- src/main/java/shop/dalda/order/domain/Order.java
- src/main/java/shop/dalda/template/application/TemplateService.java
- src/main/java/shop/dalda/template/domain/Template.java
- src/main/java/shop/dalda/template/domain/repository/TemplateRepository.java
- src/main/java/shop/dalda/template/ui/TemplateController.java
- src/main/java/shop/dalda/template/ui/dto/request/TemplateRequestDto.java
- src/main/java/shop/dalda/template/ui/dto/request/TemplateUpdateRequestDto.java
- src/main/java/shop/dalda/template/ui/dto/response/TemplateListResponseDto.java
- src/main/java/shop/dalda/template/ui/dto/response/TemplateResponseDto.java
- src/main/java/shop/dalda/template/ui/dto/response/TemplateUpdateResponseDto.java
- src/main/java/shop/dalda/user/domain/User.java
> Template 패키지 디렉토리 구조 수정

- src/main/java/shop/dalda/config/SecurityConfig.java
- src/main/java/shop/dalda/security/auth/LogoutSuccessHandler.java
- src/main/java/shop/dalda/security/jwt/TokenProvider.java
- src/main/java/shop/dalda/util/CookieUtil.java
로그아웃 시 브라우저의 쿠키(access,refresh token)를 제거하고, 
redis에서 refresh 토큰을 삭제하는 로직 추가 했습니다.
> [DD-93] 로그아웃 추가

- src/main/java/shop/dalda/user/application/UserService.java
- src/main/java/shop/dalda/user/domain/Role.java
- src/main/java/shop/dalda/user/domain/User.java
- src/main/java/shop/dalda/user/domain/repository/UserRepositoryCustom.java
- src/main/java/shop/dalda/user/domain/repository/UserRepositoryImpl.java
- src/main/java/shop/dalda/user/ui/UserController.java
- src/main/java/shop/dalda/user/ui/dto/UserAuthResponse.java
- src/main/java/shop/dalda/util/service/AuthService.java
프론트 요청시 사용할 유저정보를 조회하는 API 추가했습니다.
> [DD-97] 유저정보 조회 API 추가

- src/main/java/shop/dalda/user/ui/dto/UserAuthResponse.java
> UserAuthResponse 수정

- src/main/java/shop/dalda/security/jwt/TokenProvider.java
- src/main/java/shop/dalda/util/CookieUtil.java
쿠키 삭제시 도메인값을 명시하지 않아, 서로 다른 도메인에서의 쿠키 삭제가 불가능했었던 문제를 해결했습니다.
> [DD-99] 쿠키삭제 수정

- src/main/java/shop/dalda/security/auth/CookieAuthorizationRequestRepository.java
- src/main/java/shop/dalda/security/auth/OAuth2AuthenticationFailureHandler.java
- src/main/java/shop/dalda/security/auth/OAuth2AuthenticationSuccessHandler.java
로그인 성공 시 메인페이지로 리다이렉트 하도록 수정하였습니다.
> [DD-101] 로그인 리다이렉트 수정

- src/main/java/shop/dalda/user/application/UserService.java
- src/main/java/shop/dalda/user/domain/repository/UserRepositoryCustom.java
- src/main/java/shop/dalda/user/domain/repository/UserRepositoryImpl.java
- src/main/java/shop/dalda/user/ui/UserCompanyController.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyListResponse.java
> [DD-84] 업체 조회 api 추가

- src/main/java/shop/dalda/user/application/UserService.java
- src/main/java/shop/dalda/user/domain/User.java
- src/main/java/shop/dalda/user/ui/UserController.java
- src/main/java/shop/dalda/user/ui/dto/UserProfileImageRequest.java
- src/main/java/shop/dalda/util/service/AuthService.java
> [DD-56] 프로필 변경 API 추가

- src/main/java/shop/dalda/security/auth/LogoutSuccessHandler.java
- src/main/java/shop/dalda/security/auth/OAuth2AuthenticationSuccessHandler.java
- src/main/java/shop/dalda/security/jwt/TokenProvider.java
- src/main/java/shop/dalda/user/application/UserAuthService.java
- src/main/java/shop/dalda/user/ui/UserAuthController.java
- src/main/java/shop/dalda/user/ui/UserController.java
- src/test/java/shop/dalda/user/ui/UserControllerTest.java
accessToken을 body로 전달하도록 변경하였습니다.
> [DD-102] accessToken 전달방식 변경

- src/main/java/shop/dalda/user/domain/repository/UserRepositoryImpl.java
- src/main/java/shop/dalda/user/ui/dto/UserAuthResponse.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyRequest.java
유저정보 조회 API에 response 값을 추가했습니다.
> [DD-103] 유저정보 조회 API 수정

- src/test/java/shop/dalda/user/application/UserServiceTest.java
- src/test/java/shop/dalda/user/domain/repository/UserRepositoryTest.java
- src/test/java/shop/dalda/user/ui/UserControllerTest.java
> User 테스트 추가

- src/main/java/shop/dalda/user/ui/UserCompanyController.java
- src/main/java/shop/dalda/user/ui/UserController.java
Authentication principal 객체의 null 체크 로직이 반영되지 않았던 부분 수정했습니다.
> [DD-104] 유저정보 수정 API 수정

- src/main/java/shop/dalda/config/RedisConfig.java
- src/main/java/shop/dalda/config/RedisProperties.java
- src/test/java/shop/dalda/util/service/RedisServiceTest.java
redis 구조를 main/replica (쓰기/읽기)로 세팅하였습니다.
> [DD-105] redis master slave 쓰기 읽기 분리 configuration

- src/main/java/shop/dalda/config/RedisProperties.java
테스트 환경에서 제대로 동작하지 않아 설정을 일부 수정했습니다.
> RedisProperties 수정

- src/main/java/shop/dalda/config/SecurityConfig.java
- src/main/java/shop/dalda/config/SwaggerConfig.java
- src/main/java/shop/dalda/user/domain/Role.java
- src/main/java/shop/dalda/user/domain/User.java
- src/main/java/shop/dalda/user/domain/repository/UserRepositoryImpl.java
- src/main/java/shop/dalda/user/ui/UserAuthController.java
- src/main/java/shop/dalda/user/ui/UserCompanyController.java
- src/main/java/shop/dalda/user/ui/UserController.java
- src/test/java/shop/dalda/auth/WithMockCustomUserSecurityContextFactory.java
Spring Security 인가 설정 추가
Swagger 설정 수정
> [DD-109] spring security 인가 설정 추가

- src/main/java/shop/dalda/user/domain/repository/UserRepositoryImpl.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyResponse.java
> [DD-111] 업체 페이지 조회 API 수정

- src/main/java/shop/dalda/exception/GlobalExceptionHandler.java
- src/main/java/shop/dalda/user/domain/User.java
- src/main/java/shop/dalda/user/ui/UserCompanyController.java
- src/main/java/shop/dalda/user/ui/UserController.java
- src/main/java/shop/dalda/user/ui/dto/UserAuthResponse.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyListResponse.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyRequest.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyResponse.java
- src/main/java/shop/dalda/user/ui/dto/UserProfileImageRequest.java
- src/main/java/shop/dalda/user/ui/dto/UserUpdateRequest.java
> [DD-113] Validation 추가

- src/main/java/shop/dalda/config/SecurityConfig.java
- src/main/java/shop/dalda/user/ui/UserCompanyController.java
- src/main/java/shop/dalda/user/ui/UserHomeController.java
> [DD-124] security 수정

- appspec.yml
- scripts/deploy.sh
> [DD-10] ci/cd 설정

- .gitignore
- build.gradle
- scripts/deploy.sh
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
> Dd 10 ci cd 자동화

- src/main/java/shop/dalda/config/SecurityConfig.java
- src/main/java/shop/dalda/security/jwt/JwtAuthenticationFilter.java
- src/main/java/shop/dalda/security/jwt/JwtExceptionFilter.java
- src/main/java/shop/dalda/user/ui/UserAuthController.java
> [DD-129] 필터 수정

- src/main/java/shop/dalda/user/domain/User.java
- src/main/java/shop/dalda/user/ui/UserCompanyController.java
> [DD-137] 최근 로그인 수정

- src/main/java/shop/dalda/exception/user/UserExceptionHandler.java
- src/main/java/shop/dalda/exception/user/company/DomainDuplicatedException.java
- src/main/java/shop/dalda/user/application/UserService.java
- src/main/java/shop/dalda/user/domain/User.java
추가
CompanyDomain 유니크 인덱스
CompanyDomain 중복체크
> [DD-142] 인덱스 추가

- src/main/java/shop/dalda/user/domain/CompanyLink.java
- src/main/java/shop/dalda/user/ui/dto/UserCompanyRequest.java
> [DD-138] 컬럼명 수정

- scripts/deploy.sh
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
> [DD-139] 로그 설정
